
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pnu-rke
spec:
  selector:
    matchLabels:
      stage: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stage: dev
    spec:
      containers:
        - name: pnu-rke
          image: pnu:rke
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Seoul
---
apiVersion: v1
kind: Service
metadata:
  name: pnu-rke
  labels:
    stage: dev
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: http-port
  type: NodePort
  selector:
    stage: dev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pnu
spec:
  ingressClassName: nginx
  rules:
  - host: "pnu-rke.kw01"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pnu-rke
            port:
              number: 80
