apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namePrefix: dev-
commonLabels:
  stage: dev
images:
- name: 192.168.5.31:30005/pnu-sugang-nginx
  newTag: 20221027-015025-9
patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: pnu-sugang-nginx
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30099
