kind: ConfigMap
apiVersion: v1
metadata:
  name: onestop-log4j2-xml
data:
  log4j2.xml: >-
    <?xml version="1.0" encoding="UTF-8"?>

    <!DOCTYPE log4j:configuration PUBLIC "-//APACHE//DTD LOG4J 1.2//EN"
    "http://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/xml/doc-files/log4j.dtd">

    <Configuration>
        <properties>
            <property name="log-path">logs</property>
        </properties>
        <Appenders>

            <Console name="console" target="SYSTEM_OUT">
                <PatternLayout pattern="[%highlight{%-5level}] %d{DEFAULT} %c{1}.%M() - %msg%n%throwable{short.lineNumber}" />
            </Console>

            <!-- -->
            <RollingFile name="file" filename="${log-path}/op_onestop_log4j.log" filePattern="${log-path}/%d{yyyyMM}/op_onestop_log4j_%d{yyyyMMdd}.log"
                append="false">
                <PatternLayout pattern="%d{yyyy.MM.dd hh:mm:ss,SSS} %5p [%c::%M] %m%n" />

                <Policies>
                    <!-- interval(default 1)이므로 1초 간격으로 rolling 수행 intervar속성 추가 -->
                    <TimeBasedTriggeringPolicy interval="1" />
                    <!-- 사이즈 제한을 하고 싶을 경우 아래 속성 추가 -->
                    <!-- <SizeBasedTriggeringPolicy size="250 MB"/> -->
                </Policies>
            </RollingFile>

        </Appenders>

        <Loggers>
            <!-- log SQL with timing information, post execution -->
            <Root level="ERROR">
                <AppenderRef ref="console" />
                <AppenderRef ref="file" />
            </Root>

            <Logger name="egovframework" level="ERROR" additivity="false">
                <AppenderRef ref="console" />
                <AppenderRef ref="file" />
            </Logger>
            <Logger name="java.sql" level="ERROR" additivity="false">
                <AppenderRef ref="console" />
                <AppenderRef ref="file" />
            </Logger>
            <Logger name="com.pnu" level="ERROR" additivity="false">
                <AppenderRef ref="console" />
                <AppenderRef ref="file" />
            </Logger>
            <Logger name="org.springframework" level="ERROR" additivity="false">
                <AppenderRef ref="console" />
                <AppenderRef ref="file" />
            </Logger>
            <!-- 
            <Logger name="jdbc.sqlonly" level="ERROR" additivity="false">
                <AppenderRef ref="console" />
                <AppenderRef ref="file" />
            </Logger>
            --> 
            <Logger name="log4jdbc.log4j2" level="ERROR" additivity="false">
                <AppenderRef ref="console" />
                <AppenderRef ref="file" />
            </Logger>

            <!-- SQL Logger -->
     
            <logger name="jdbc.sqltiming" additivity="false">
                <level value="debug" />
                <appender-ref ref="console" />
            </logger>

            <logger name="jdbc.sqlonly" additivity="false">
                <level value="debug" />
                <appender-ref ref="console" />
            </logger>

            <logger name="jdbc.audit" additivity="false">
                <level value="debug" />
                <appender-ref ref="console" />
            </logger>

            <logger name="jdbc.resultset" additivity="false">
                <level value="debug" />
                <appender-ref ref="console" />
            </logger>
     
            <logger name="jdbc.resultsettable" additivity="false">
                <level value="debug" />
                <appender-ref ref="console" />
            </logger>

        </Loggers>
    </Configuration>

