kind: ConfigMap
apiVersion: v1
metadata:
  name: one-context-xml
data:
  context.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <Context allowCasualMultipartParsing="true">
        <WatchedResource>WEB-INF/web.xml</WatchedResource>
        <WatchedResource>WEB-INF/tomcat-web.xml</WatchedResource>
        <WatchedResource>WEB-INF/websquare_home/config/websquare.xml</WatchedResource>
        <Resources cachingAllowed="true" cacheMaxSize="100000" />
        <CookieProcessor sameSiteCookies="none"/>
    </Context>
