apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- service.yaml
- ingress.yaml
- config/onestop-context.yaml
- config/one-db-properties.yaml
- config/onestop-log4j2-xml.yaml
- config/onestop-server.yaml

images:
- name: 192.168.5.31:30005/onestop
  newTag: 20221027-013838-1
