apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-svn-git-every-hour
  namespace: svn
spec:
  jobTemplate:
    metadata:
      namespace: svn
    spec:
      template:
        spec:
          containers:
            - args:
                - sync-svn-git.sh
              command:
                - /bin/bash
              image: svn:dev
              imagePullPolicy: IfNotPresent
              name: sync-svn-git
              volumeMounts:
                - mountPath: /root/sync-svn-git.sh
                  name: sync-svn-git
                  subPath: sync-svn-git.sh
              workingDir: /root
          schedulerName: default-scheduler
          volumes:
            - configMap:
                defaultMode: 420
                name: sync-svn-git
              name: sync-svn-git
  schedule: 0 * * * *
