apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: onestop-build-listener
spec:
  serviceAccountName: sa-pipeline-trigger
  triggers:
    - name: onestop-build-trigger
      interceptors:
        - name: "CEL filter: only master brancher pushed"
          ref:
            name: "cel"
          params:
          - name: "filter"
            value: "body.ref in ['refs/heads/master']"
      bindings:
        - ref: onestop-build-binding
      template:
        ref: onestop-build-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: onestop-build-binding
spec:
  params:
    - name: git-revision
      value: $(body.after)
    - name: git-repository-url
      value: $(body.repository.clone_url)
    - name: git-repo-name
      value: $(body.repository.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: onestop-build-template
spec:
  params:
    - name: git-revision
      description: The git revision
    - name: git-repository-url
      description: The git repository url
    - name: git-repo-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: trigger-onestop-jib-build-
      spec:
        serviceAccountName: sa-pipeline-runner
        pipelineRef:
          name: build-mvn-jib
        params:
        - name: build-stage
          value: dr
        - name: git-repo-name
          value: pnu
        - name: git-branch
          value: master
        - name: insecure-registry
          value: "true"
        - name: git-url
          value: "http://gitea.gitea:3000/gitea"
        - name: image-url
          value: "192.168.5.31:30005"
        - name: gitops-repo-name
          value: onestop-deploy
        - name: gitops-branch
          value: kust
        workspaces:
        - name: source
          persistentvolumeclaim:
            claimName: pvc-build
          subPath: onestop
        - name: gitops
          emptyDir: {}
