apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: onestop-jib-build-pipeline-
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
    name: build-mvn-jib
  params:
  - name: build-stage
    value: dev
  - name: git-repo-name
    value: onestop
  - name: git-branch
    value: master
  - name: insecure-registry
    value: "true"
  - name: git-url
    value: "http://gitea.gitea:3000/gitea"
  - name: image-url
    value: "192.168.5.31:30005"
  - name: gitops-repo-name
    value: onestop-deploy
  - name: gitops-branch
    value: kust
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-build
    subPath: onestop
  - name: gitops
    emptyDir: {}
