apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-svn-git
data:
  sync-svn-git.sh: |-
    #!/bin/bash    
     cd $HOME    
     rm -rf workspace 
     mkdir workspace && cd workspace  
     echo "=== CHECKOUT SVN REPO ==="   
     svn co --username $SVN_ID --password $SVN_PWD svn://$SVN_URL/$SVN_REPO --non-interactive
     sed -i 's/192.168.2.144:8081/nexus-dr.pnu.ac.kr/g' $SVN_REPO/pom.xml

     echo "=== CONFIG GIT ==="    
     echo "http://gitea:gitea123@gitea-dr.pnu.ac.kr" > ~/.git-credentials   
     git config --global user.email tekton@pun.ac.kr   
     git config --global credential.helper store    

     echo "=== CLONE GIT ==="   
     git clone http://gitea-dr.pnu.ac.kr/gitea/$GIT_REPO tmp   

     echo "=== ADD MIRROR DATE ==="   
     rm -f tmp/SVN_MIRROR_DATE   
     echo "SVN repo mirrored at" + $(date +%F-%H-%M-%S) > tmp/SVN_MIRROR_DATE   

     echo "=== COPY SVN to GIT ==="    
     cp -R $SVN_REPO/* tmp/    
     cd tmp    
     git add .    
     git commit -m "update: SVN source $(date)"    
     git push -u origin master
