apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pnu-sugang-nginx-build-pipeline-
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
    name: build-buildah
  params:
  - name: build-stage
    value: dev
  - name: git-repo-name
    value: pnu-sugang-nginx
  - name: git-branch
    value: main
  - name: insecure-registry
    value: "false"
  - name: git-url
    value: "http://gitea.gitea:3000/gitea"
  - name: image-url
    value: "192.168.5.31:30005"
  - name: gitops-repo-name
    value: pnu-sugang-nginx-deploy
  - name: gitops-branch
    value: main
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-build
  - name: gitops
    emptyDir: {}
