apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namePrefix: dev-
commonLabels:
  stage: dev
images:
- name: 192.168.5.31:30005/onestop
  newTag: dev-231109-030239-4918e6cf
patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: onestop
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30077
