---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: dev
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-pvc
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: dev-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: dev
spec:
  selector:
    matchLabels:
      app: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - name: dev
        image: dev:sh
        imagePullPolicy: IfNotPresent
        env:
          - name: TZ
            value: Asia/Seoul
        volumeMounts:
        - name: dev-volume
          mountPath: /root/works
      volumes:
        - name: dev-volume
          persistentVolumeClaim:
            claimName: dev-pvc
